version: "3.9"

services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    user: "1883:1883"
    restart: unless-stopped
    networks:
      - iot_network

  api_gateway:
    build: .
    container_name: gateway_api
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
      - mongodb
    environment:
      - MQTT_BROKER_HOST=mosquitto
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/
    restart: unless-stopped
    networks:
      - iot_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - iot_network

networks:
  iot_network:
    driver: bridge

volumes:
  mongodb_data:
  mosquitto_data:
  mosquitto_log:
